## Put comments here that give an overall description of what your
## functions do

## makeCacheMatrix function accepts the matrix as an imput value, creates a list of functions:
##set - passes new matrix value into original matrix
##get - returns current values of the matrix
##setSolve - passes the value of the inverse matrix to upper level variable inverseMatrix which exists outside of makeCacheMatrix environment
##getSolve - returns the current valu of the inverseMatrix

makeCacheMatrix <- function(originalMatrix = matrix()) {
    inverseMatrix <- NULL
    set <- function(newMatrix) {
        originalMatrix <<- newMatrix
        inverseMatrix <<- NULL
    }
    get <- function() originalMatrix
    setSolve <- function(solve) inverseMatrix <<- solve
    getSolve <- function() inverseMatrix
    list(set = set, get = get,
         setSolve = setSolve,
         getSolve = getSolve)

}


## cacheSolve accepts the cached matrix (list) generated by makeCacheMatrix
## it pulls the value of the inverse matrix stored in inverseMatrix outside of the makeCacheMatrix and cheks for null
## if it is not null it return inverseMatrix value
## if it is null it performs solve operation assign it to inverseMatrix stored outside of the cacheSolve and makeCacheMatrix environment and returns its value.

cacheSolve <- function(cachedMatrix, ...) {
        ## Return a matrix that is the inverse of 'x'
    inverseXMatrix <- cachedMatrix$getSolve()
    if(!is.null(inverseXMatrix)) {
        message("getting cached data")
        return(inverseXMatrix)
    }
    data <- cachedMatrix$get()
    inverseXMatrix <- solve(data,...)
    cachedMatrix$setSolve(inverseXMatrix)
    inverseXMatrix
}
